begin;
select plan(35);
select has_table('public','patients','patients table exists');
select has_table('public','visits','visits table exists');
select has_table('public','medicine_batches','stock table exists');
select has_function('public','create_visit_with_token',array['uuid','uuid','visit_type','bigint','bigint','payment_mode','uuid','text','uuid'],'atomic visit RPC exists');
select has_function('public','dispense_prescription',array['uuid','jsonb','payment_mode','uuid'],'atomic dispense RPC exists');
select has_function('public','record_visit_vitals',array['uuid','numeric','numeric','numeric','smallint','smallint','smallint','smallint','smallint','text'],'vitals workflow RPC exists');
select has_function('public','save_visit_consultation',array['uuid','text','text','text','text','text','follow_up_type','date','integer','jsonb','jsonb','boolean'],'consultation workflow RPC exists');
select has_function('public','create_ip_ticket',array['uuid','uuid','uuid','text','text','text','bigint','payment_mode','uuid'],'IP admission RPC exists');
select has_trigger('public','consultations','protect_completed_consultation','completed consultations are immutable');
select has_trigger('public','prescription_items','protect_prescription_content','completed prescription content is immutable');
select has_trigger('public','visit_payments','prevent_visit_overpayment','visit overpayment is blocked');
select has_function('public','bulk_import_medicines',array['jsonb','text','uuid'],'bulk medicine import RPC exists');
select has_function('public','add_ip_progress_note',array['uuid','text','boolean','uuid'],'IP progress note RPC exists');
select has_function('public','save_ip_discharge_summary',array['uuid','text','text','text','text','text','text'],'IP discharge summary RPC exists');
select has_function('public','complete_ip_discharge',array['uuid'],'IP discharge completion RPC exists');
select has_trigger('public','ip_tickets','protect_ip_discharge_workflow','IP discharge is a controlled immutable workflow');
select has_trigger('public','patients','audit_patient_created','patient creation is audited at the database boundary');
select has_trigger('public','patient_reports','audit_patient_report','report upload metadata is audited at the database boundary');
select col_has_check('public','patient_reports','size_bytes','patient report metadata enforces the 1 MB limit');
select has_table('public','stock_movements','stock movement ledger exists');
select has_function('public','save_medicine_batch',array['uuid','uuid','text','date','integer','bigint','bigint','integer','boolean','text','uuid'],'atomic stock adjustment workflow exists');
select has_function('public','review_patient_report',array['uuid'],'controlled doctor report review exists');
select has_trigger('public','patient_reports','validate_report_relationship','report links are validated at the database boundary');
select has_function('public','report_admin_overview',array['date','date'],'server-side admin analytics exists');
select has_function('public','search_medicine_availability',array['text','integer'],'doctor-safe medicine availability RPC exists');
select has_function('public','list_pharmacy_batches',array['integer','integer'],'guarded pharmacy batch listing exists');
select has_function('public','list_medicine_directory',array['text','integer','integer'],'guarded medicine directory listing exists');
select has_function('public','list_available_dispense_batches',array['integer'],'guarded FEFO dispensing batch list exists');
select has_function('public','operational_data_signature',array[]::text[],'cost-controlled live data signature exists');
select has_function('public','get_visit_financial_summaries',array['uuid[]'],'guarded visit finance RPC exists');
select has_trigger('public','vitals','protect_closed_visit_vitals','closed visit vitals are immutable');
select has_trigger('public','prescriptions','protect_prescription_status','prescription lifecycle is protected');
select col_is_pk('public','patients','id','patient internal identity is UUID primary key');
select col_has_check('public','medicine_batches','quantity','stock has a non-negative check');
select isnt_empty($$select policyname from pg_policies where schemaname='public' and tablename='patients'$$,'patients have RLS policies');
select * from finish();
rollback;
