"use client";
import { useActionState,useState } from "react";
import { FileCheck2,LoaderCircle,NotebookPen,Stethoscope } from "lucide-react";
import { addProgressNote,completeDischarge,saveDischargeSummary } from "./actions";
import type { ActionState } from "@/types/hospital";
import { Alert,AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAutoCloseDialog } from "@/hooks/use-auto-close-dialog";
const initial:ActionState={ok:false};
export function ProgressNoteDialog({ticketId,defaultFee}:{ticketId:string;
  /** Doctor's configured IP visit fee in rupees; a suggestion, always editable. */
  defaultFee?:string}){
  const[state,action,pending]=useActionState(addProgressNote,initial);
  const[key]=useState(()=>crypto.randomUUID());
  const[chargeable,setChargeable]=useState(false);
  const[fee,setFee]=useState(defaultFee??"");
  const{open,setOpen}=useAutoCloseDialog(state,"Progress note saved.");
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button size="sm" variant="outline"/>}><NotebookPen/> Progress Note</DialogTrigger><DialogContent><form action={action} className="contents"><DialogHeader><DialogTitle>Add progress note</DialogTitle><DialogDescription>A chargeable visit adds one doctor charge to the IP ticket, exactly once.</DialogDescription></DialogHeader><input type="hidden" name="ticketId" value={ticketId}/><input type="hidden" name="idempotencyKey" value={key}/><input type="hidden" name="chargeable" value={chargeable?"on":""}/>{state.message&&!state.ok?<Alert variant="destructive"><AlertDescription>{state.message}</AlertDescription></Alert>:null}<div className="space-y-2"><Label htmlFor="progress-note">Clinical note</Label><Textarea id="progress-note" name="note" rows={6} required/></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={chargeable} onCheckedChange={(checked)=>setChargeable(checked===true)}/> Charge as an IP doctor visit</label>{/* A ward round and a detailed review are not worth the same, and the
      doctor may waive the charge, so the amount is typed here rather than
      always taken from their configured fee. */}
{chargeable?<div className="max-w-xs space-y-2"><Label htmlFor="progress-fee">Visit charge (₹)</Label><Input id="progress-fee" name="fee" inputMode="decimal" value={fee} onChange={(event)=>setFee(event.target.value)} placeholder="500"/><p className="text-xs text-muted-foreground">Pre-filled with the configured IP visit fee. Enter 0 to record the visit without charging.</p><p className="text-xs text-destructive">{state.fieldErrors?.fee?.[0]}</p></div>:null}<DialogFooter showCloseButton><Button disabled={pending} type="submit">{pending?<LoaderCircle className="animate-spin"/>:<NotebookPen/>} Save Note</Button></DialogFooter></form></DialogContent></Dialog>}
export function DischargeSummaryDialog({ticketId,initialValues}:{ticketId:string;initialValues?:Record<string,string|null>}){const[state,action,pending]=useActionState(saveDischargeSummary,initial);const{open,setOpen}=useAutoCloseDialog(state,"Discharge summary saved.");const fields=[["finalDiagnosis","Final Diagnosis",true],["hospitalCourse","Hospital Course",true],["treatmentSummary","Treatment",false],["dischargeMedicines","Discharge Medicines",false],["dischargeAdvice","Advice",true],["followUp","Follow-up",false]] as const;return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button size="sm"/>}><Stethoscope/> Prepare Discharge</DialogTrigger><DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto sm:max-w-2xl"><form action={action} className="contents"><DialogHeader><DialogTitle>Clinical discharge summary</DialogTitle><DialogDescription>Saving moves the ticket to Discharge Pending. IP staff completes billing and discharge.</DialogDescription></DialogHeader><input type="hidden" name="ticketId" value={ticketId}/>{state.message&&!state.ok?<Alert variant="destructive"><AlertDescription>{state.message}</AlertDescription></Alert>:null}<div className="grid gap-4 sm:grid-cols-2">{fields.map(([name,label,required])=><div className={`space-y-2 ${["hospitalCourse","treatmentSummary"].includes(name)?"sm:col-span-2":""}`} key={name}><Label htmlFor={`discharge-${name}`}>{label}{required?" *":""}</Label><Textarea id={`discharge-${name}`} name={name} defaultValue={initialValues?.[name]??""} rows={name==="hospitalCourse"?5:3} required={required}/><p className="text-xs text-destructive">{state.fieldErrors?.[name]?.[0]}</p></div>)}</div><DialogFooter showCloseButton><Button disabled={pending} type="submit">{pending?<LoaderCircle className="animate-spin"/>:<FileCheck2/>} Save Summary</Button></DialogFooter></form></DialogContent></Dialog>}
export function CompleteDischargeDialog({ticketId,balancePaise}:{ticketId:string;balancePaise:number}){const[state,action,pending]=useActionState(completeDischarge,initial);const{open,setOpen}=useAutoCloseDialog(state,"Discharge completed.");return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button size="sm" disabled={balancePaise>0}/>}><FileCheck2/> Complete Discharge</DialogTrigger><DialogContent><form action={action} className="contents"><DialogHeader><DialogTitle>Complete discharge?</DialogTitle><DialogDescription>This records the final discharge time. Historical charges, payments, and clinical notes remain immutable.</DialogDescription></DialogHeader><input type="hidden" name="ticketId" value={ticketId}/>{balancePaise>0?<Alert variant="destructive"><AlertDescription>Outstanding balance must be collected first.</AlertDescription></Alert>:null}{state.message&&!state.ok?<Alert variant="destructive"><AlertDescription>{state.message}</AlertDescription></Alert>:null}<DialogFooter showCloseButton><Button disabled={pending||balancePaise>0} type="submit">{pending?<LoaderCircle className="animate-spin"/>:<FileCheck2/>} Confirm Discharge</Button></DialogFooter></form></DialogContent></Dialog>}
